# @Author: Haibin Lee <haibin>
# @Date:   2021-01-25T12:27:13+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: WeBASE-Sign.yml
# @Last modified by:   haibin
# @Last modified time: 2021-01-25T13:34:55+08:00
# @Copyright: Copyright 2020 the original author or authors.

- name: 拉取代码
  git:
    repo: https://github.com/WeBankFinTech/WeBASE-Sign.git
    dest: "{{ ansible_env.HOME }}/WeBASE-Sign"
    depth: 1
    force: true

# - name: "创建 {{ ansible_env.HOME }}/WeBASE-Sign/.m2"
#   file:
#     path: "{{ ansible_env.HOME }}/WeBASE-Sign/.m2"
#     state: directory
#     owner: "1000"
#     group: "1000"
#     recurse: true

- name: "使用 gradle:{{ webase_sign.gradle_version }} 容器编译代码"
  docker_container:
    name: "build-webase"
    image: "gradle:{{ webase_sign.gradle_version }}"
    env:
      TIME_ZONE: Asia/Shanghai
    volumes:
      # - "{{ ansible_env.HOME }}/WeBASE-Sign/.m2:/root/.m2"
      - "{{ ansible_env.HOME }}/WeBASE-Sign:/home/gradle/project"
    working_dir: "/home/gradle/project"
    detach: no
    cleanup: yes
    command: "gradle build -x test"

- name: "建立 {{ ansible_env.HOME }}/WeBASE-Sign/dist/conf 软链接"
  file:
    src:
